name: Auto build Aseprite

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  auto-build:
    name: Auto build Aseprite for macOS
    runs-on: macos-14  # Use macOS runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Homebrew dependencies
        run: |
          brew install cmake ninja libpng jpeg freetype giflib

      - name: Set up Python Virtual Environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download Aseprite and dependencies
        run: |
          source venv/bin/activate
          python download.py

      - name: Build Skia
        run: |
          source venv/bin/activate
          cd ~/deps/skia
          python tools/git-sync-deps
          gn gen out/Release-arm64 --args="is_debug=false is_official_build=true skia_use_system_expat=false skia_use_system_icu=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false skia_use_sfntly=false skia_use_freetype=true skia_use_harfbuzz=true skia_pdf_subset_harfbuzz=true skia_use_system_freetype2=false skia_use_system_harfbuzz=false target_cpu=\"arm64\" extra_cflags=[\"-stdlib=libc++\", \"-mmacosx-version-min=11.0\"] extra_cflags_cc=[\"-frtti\"]"
          ninja -C out/Release-arm64 skia modules

      - name: Build Aseprite
        run: |
          source venv/bin/activate
          mkdir build
          cd build
          cmake \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_OSX_ARCHITECTURES=arm64 \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0 \
            -DCMAKE_OSX_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk \
            -DLAF_BACKEND=skia \
            -DSKIA_DIR=~/deps/skia \
            -DSKIA_LIBRARY_DIR=~/deps/skia/out/Release-arm64 \
            -DSKIA_LIBRARY=~/deps/skia/out/Release-arm64/libskia.a \
            -DPNG_ARM_NEON:STRING=on \
            -G Ninja \
            ..
          ninja aseprite

      - name: Get Version
        id: get_version
        run: |
          version=$(cat version.txt)
          echo "version=$version" >> $GITHUB_ENV

      - name: Zip Aseprite
        run: |
          cd build/bin
          zip -r ../../Aseprite-macOS-${{ env.version }}.zip *

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2.0.4
        with:
          name: Aseprite-macOS-${{ env.version }}
          tag_name: ${{ env.version }}
          files: |
            Aseprite-macOS-${{ env.version }}.zip